<a href="https://colab.research.google.com/github/SolMile/mile/blob/main/tutoria.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!python --version
import numpy as np

Python 3.10.12


In [8]:
mile=np.array([3,33,333])
print(mile)
#ver dimension
print(mile.shape)
#indice es localizacion


[  3  33 333]
(3,)


In [13]:
b=np.zeros((4,6))
b
print(b.shape)
print(b)
b[3,3]=123
print(b)
print(b[:,[2,3]])

print(b[:,[3,2]])

(4, 6)
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 123.   0.   0.]]
[[  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0. 123.]]
[[  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [123.   0.]]


In [17]:
c=np.random.randint(low=4,high=12,size=(4,5))
c
#print(c)

array([[10, 11,  4, 11,  6],
       [ 4,  9, 11,  4,  5],
       [11,  8,  4,  6,  6],
       [ 8, 10, 10, 10,  7]])

In [23]:
c=np.random.randint(low=4,high=12,size=(2,2))
d=np.random.randint(low=1,high=8,size=(2,2))




In [20]:
c

array([[ 7,  4],
       [ 6, 10]])

In [24]:
d

array([[1, 6],
       [7, 6]])

In [25]:
#vertical
aux=np.vstack((c,d))
print(aux)

[[11  7]
 [ 4 10]
 [ 1  6]
 [ 7  6]]


In [26]:
#horizontal
aux=np.hstack((c,d))
print(aux)

[[11  7  1  6]
 [ 4 10  7  6]]


In [27]:
c=np.random.randint(low=4,high=12,size=(9))
print(c)
print(c.shape)

[ 7 11  9  9  7  9  9 10  7]
(9,)
